Update terraformpoc.yml

diff --git a/.github/workflows/terraformpoc.yml b/.github/workflows/terraformpoc.yml
--- a/.github/workflows/terraformpoc.yml
+++ b/.github/workflows/terraformpoc.yml
@@ -72,14 +72,26 @@ jobs:
                     formdestroycommand+=" -target=$module"
                 done
             
-                terraform plan -destroy -var-file=<(cat ${autotfvars[*]}) $formdestroycommand -no-color -out tfdestroyplan || export exitcode=$?
-                echo "exitcode=$exitcode" >>$GITHUB_OUTPUT
+                if [[ "${#autotfvars[@]}" -gt 1 ]]; then
+                    terraform plan -destroy -var-file=<(cat ${autotfvars[*]}) $formdestroycommand -no-color -out tfdestroyplan || export exitcode=$?
+                    echo "exitcode=$exitcode" >>$GITHUB_OUTPUT
             
-                if [ "$exitcode" -eq 1 ]; then
-                    echo "Terraform Destroy Plan Failed!"
-                    exit 1
+                    if [ "$exitcode" -eq 1 ]; then
+                        echo "Terraform Destroy Plan Failed!"
+                        exit 1
+                    else
+                        exit 0
+                    fi
                 else
-                    exit 0
+                    terraform plan -destroy -var-file=<(cat "${autotfvars[0]}") $formdestroycommand -no-color -out tfdestroyplan || export exitcode=$?
+                    echo "exitcode=$exitcode" >>$GITHUB_OUTPUT
+            
+                    if [ "$exitcode" -eq 1 ]; then
+                        echo "Terraform Destroy Plan Failed!"
+                        exit 1
+                    else
+                        exit 0
+                    fi
                 fi
             
             elif [[ "$TF_DESTROY" == "tfstate" ]]; then
