Update terraformpoc.yml

diff --git a/.github/workflows/terraformpoc.yml b/.github/workflows/terraformpoc.yml
--- a/.github/workflows/terraformpoc.yml
+++ b/.github/workflows/terraformpoc.yml
@@ -56,26 +56,54 @@ jobs:
             export exitcode=0
             autotfvars=()
             for file in $(ls dev/); do
-            	if [[ "$file" == *auto.tfvars ]]; then
-            		autotfvars+=($PWD/dev/$file)
-            	fi
+                if [[ "$file" == *auto.tfvars ]]; then
+                    autotfvars+=("$PWD/dev/$file")
+                fi
             done
             echo "==============================="
-            echo ${autotfvars[0]}
-            echo ${autotfvars[*]}
-            echo $PWD
+            echo "${autotfvars[0]}"
+            echo "${autotfvars[*]}"
+            echo "$PWD"
             echo "+++++++++++++++++++++++++++++"
-            if [[ "${#autotfvars[@]}" -gt 1 ]] ; then
-              
-              terraform plan -destroy -var-file=<(cat ${autotfvars[*]}) -target="module.rg.azurerm_resource_group.rg" -target="module.rg.azurerm_service_plan.example" -no-color -out tfdestroyplan || export exitcode=$?
-              echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-              
-              if [ $exitcode -eq 1 ]; then
-                echo Terraform Destroy Plan Failed!
-                exit 1
-              else 
-                exit 0
-              fi
+            
+            if [[ "$TF_DESTROY" == "targetmodules" ]]; then
+                deletemodules=(module.rg.azurerm_resource_group.rg module.rg.azurerm_service_plan.example)
+                for module in "${deletemodules[@]}"; do
+                    formdestroycommand+=" -target=$module"
+                done
+            
+                terraform plan -destroy -var-file=<(cat ${autotfvars[*]}) $formdestroycommand -no-color -out tfdestroyplan || export exitcode=$?
+                echo "exitcode=$exitcode" >>$GITHUB_OUTPUT
+            
+                if [ "$exitcode" -eq 1 ]; then
+                    echo "Terraform Destroy Plan Failed!"
+                    exit 1
+                else
+                    exit 0
+                fi
+            
+            elif [[ "$TF_DESTROY" == "tfstate" ]]; then
+                if [[ "${#autotfvars[@]}" -gt 1 ]]; then
+                    terraform plan -destroy -var-file=<(cat "${autotfvars[*]}") -no-color -out tfdestroyplan || export exitcode=$?
+                    echo "exitcode=$exitcode" >>$GITHUB_OUTPUT
+            
+                    if [ "$exitcode" -eq 1 ]; then
+                        echo "Terraform Destroy Plan Failed!"
+                        exit 1
+                    else
+                        exit 0
+                    fi
+                else
+                    terraform plan -destroy -var-file=<(cat "${autotfvars[0]}") -no-color -out tfdestroyplan || export exitcode=$?
+                    echo "exitcode=$exitcode" >>$GITHUB_OUTPUT
+            
+                    if [ "$exitcode" -eq 1 ]; then
+                        echo "Terraform Destroy Plan Failed!"
+                        exit 1
+                    else
+                        exit 0
+                    fi
+                fi
             fi
                 
       - name: Terraform destroy
